### ISSUE TITLE
Publish v0.0.1!

### ISSUE THREAD

**Issue by isaac-mason** [isaac-mason/recast-navigation-js#1]
### TODO
- [x] [Create build & test github action
](https://github.com/isaac-mason/recast-navigation-js/issues/2)
- [x] [Set up storybook deployment
](https://github.com/isaac-mason/recast-navigation-js/issues/3)
- [x] [Create changesets github action 
](https://github.com/isaac-mason/recast-navigation-js/issues/4)
- [x] [Implement NavMeshHelper obstacle functionality](https://github.com/isaac-mason/recast-navigation-js/issues/6)
- [x] [Configure storybook source addon](https://github.com/isaac-mason/recast-navigation-js/issues/7)
- [x] Add more storybooks
